strategy: round_robin
otlp_endpoint: "http://otel-collector:4317"
otlp_protocol: "grpc"

runtime:
  metrics_cap: 1000
  health_cap: 100
  drain_timeout_millis: 2000
  background_timeout_millis: 2000
  accept_timeout_millis: 5000
  config_watch_interval_millis: 1000

proxy:
  listen_address: "0.0.0.0:50501"
  max_connections: 10000

backends:
  - id: 0
    name: worker-1
    address: "worker-actix:50510"
    weight: 1
  - id: 1
    name: worker-2
    address: "worker-axum:50520"
    weight: 1
  - id: 2
    name: worker-3
    address: "worker-hyper:50530"
    weight: 1
  - id: 3
    name: worker-4
    address: "worker-rocket:50540"
    weight: 1

health:
  interval: 10000
  timeout: 5000

metrics:
  interval: 10000
  timeout: 5000

  