[runtime]
metrics_cap = 100
health_cap = 50
drain_timeout_millis = 5000
background_timeout_millis = 1000
accept_timeout_millis = 2000

[proxy]
listen_address = "127.0.0.1:50501"
max_connections = 1000

strategy = "fastest_response_time"

[[backends]]
id = 1
name = "worker-1"
address = "127.0.0.1:50510"

[[backends]]
id = 2
name = "worker-2"
address = "127.0.0.1:50520"

[[backends]]
id = 3
name = "worker-3"
address = "127.0.0.1:50530"

[[backends]]
id = 4
name = "worker-4"
address = "127.0.0.1:50540"

[health]
interval = 30000
timeout = 30000

[metrics]
interval = 10000
timeout = 10000

